# Generated by Django 4.0.10 on 2023-10-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school',
            new_name='current_school',
        ),
        migrations.AddField(
            model_name='user',
            name='target_school',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
