# Generated by Django 4.0.10 on 2023-10-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_school_user_current_school_user_target_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_path',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
