# Generated by Django 4.0.8 on 2023-02-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
