# Generated by Django 4.0.8 on 2023-02-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
