# Generated by Django 4.1.4 on 2023-01-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vesrion', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('sub_title', models.CharField(max_length=140)),
                ('author', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('isbn', models.CharField(max_length=140)),
                ('company', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('types', models.CharField(choices=[('book', 'Book'), ('lecture', 'Lecture')], max_length=8)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=140)),
                ('company', models.CharField(max_length=140)),
                ('target_url', models.CharField(default='', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vesrion', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('sub_title', models.CharField(max_length=140)),
                ('author', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('company', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('followers_num', models.PositiveIntegerField()),
                ('category', models.ManyToManyField(blank=True, to='categories.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
