# Generated by Django 4.1.4 on 2023-01-02 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='books',
            field=models.ManyToManyField(blank=True, to='contents.book'),
        ),
        migrations.AddField(
            model_name='content',
            name='books',
            field=models.ManyToManyField(blank=True, to='contents.book'),
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ManyToManyField(blank=True, to='categories.category'),
        ),
        migrations.AddField(
            model_name='content',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='lectures',
            field=models.ManyToManyField(blank=True, to='contents.lecture'),
        ),
        migrations.AddField(
            model_name='content',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='contents.track'),
        ),
    ]
