# Generated by Django 4.1.4 on 2023-01-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_content_books_alter_content_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='unique_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='unique_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
