# Generated by Django 4.1.4 on 2023-01-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_book_unique_id_lecture_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='followers_num',
        ),
    ]
