# Generated by Django 4.0.8 on 2023-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_track_followers_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
