# Generated by Django 4.1.4 on 2023-01-17 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0004_book_unique_id_lecture_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('content', models.ManyToManyField(related_name='lovings', to='contents.content')),
                ('track', models.ManyToManyField(related_name='lovings', to='contents.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lovings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
