# Generated by Django 4.0.8 on 2023-02-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_content_content_parent_alter_book_image_and_more'),
        ('reviews', '0004_review_rating_1_review_rating_2_review_rating_3_and_more'),
        ('lovings', '0003_loving_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loving',
            name='contents',
            field=models.ManyToManyField(blank=True, related_name='lovings', to='contents.content'),
        ),
        migrations.AlterField(
            model_name='loving',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='lovings', to='reviews.review'),
        ),
        migrations.AlterField(
            model_name='loving',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='lovings', to='contents.track'),
        ),
    ]
