# Generated by Django 4.0.8 on 2023-02-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replys', '0001_initial'),
        ('lovings', '0004_alter_loving_contents_alter_loving_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loving',
            name='replys',
            field=models.ManyToManyField(related_name='lovings', to='replys.reply'),
        ),
    ]
