# Generated by Django 4.0.8 on 2023-07-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workbooks', '0001_initial'),
        ('workbook_evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook_evaluation',
            name='workbook',
            field=models.ManyToManyField(blank=True, related_name='workbook_evaluations', to='workbooks.workbook'),
        ),
    ]
