# Generated by Django 4.0.10 on 2023-10-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='decision',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
