# Generated by Django 4.1.4 on 2023-01-03 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0003_alter_content_books_alter_content_category_and_more'),
        ('followings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='content',
        ),
        migrations.RemoveField(
            model_name='following',
            name='follow_date',
        ),
        migrations.RemoveField(
            model_name='following',
            name='kind',
        ),
        migrations.AlterField(
            model_name='following',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followings', to='contents.track'),
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
