# Generated by Django 4.1.4 on 2023-01-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followings', '0003_remove_following_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
