# Generated by Django 4.1.4 on 2023-01-17 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_content_books_alter_content_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followings', '0004_following_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='track',
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='following',
            name='track',
            field=models.ManyToManyField(null=True, related_name='followings', to='contents.track'),
        ),
    ]
