# Generated by Django 4.0.8 on 2023-01-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_track_followers_num'),
        ('followings', '0006_alter_following_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='track',
        ),
        migrations.AddField(
            model_name='following',
            name='tracks',
            field=models.ManyToManyField(null=True, related_name='followings', to='contents.track'),
        ),
    ]
