# Generated by Django 4.0.8 on 2023-01-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_track_followers_num'),
        ('followings', '0007_remove_following_track_following_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='tracks',
            field=models.ManyToManyField(related_name='followings', to='contents.track'),
        ),
    ]
