# Generated by Django 4.1.4 on 2023-01-03 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0003_alter_content_books_alter_content_category_and_more'),
        ('tasks', '0001_initial'),
        ('followlists', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followlist',
            name='tasks',
            field=models.ManyToManyField(related_name='followlists', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='followlist',
            name='tracks',
            field=models.ManyToManyField(related_name='followlists', to='contents.track'),
        ),
        migrations.AlterField(
            model_name='followlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
