# Generated by Django 4.1.4 on 2023-01-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_track_followers_num'),
        ('followlists', '0003_alter_followlist_tasks_alter_followlist_tracks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followlist',
            name='tracks',
        ),
        migrations.AddField(
            model_name='followlist',
            name='tracks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followlists', to='contents.track'),
        ),
    ]
