# Generated by Django 4.1.4 on 2023-01-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followlists', '0004_remove_followlist_tracks_followlist_tracks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followlist',
            old_name='tracks',
            new_name='track',
        ),
    ]
