# Generated by Django 4.0.10 on 2023-09-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_days', '0001_initial'),
        ('difficult_questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_taken', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField()),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('difficult_question', models.ManyToManyField(blank=True, related_name='task_evaluations', to='difficult_questions.difficult_question')),
                ('task_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_evaluations', to='task_days.task_day')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
