# Generated by Django 4.0.10 on 2023-09-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_days', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_guidelines', to='task_days.task_day')),
            ],
            options={
                'verbose_name': 'Task Guideline',
                'verbose_name_plural': 'Task Guidelines',
            },
        ),
    ]
