# Generated by Django 4.1.4 on 2023-01-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('kind_major', models.CharField(choices=[('contents', 'Contents'), ('tracks', 'Tracks')], max_length=15)),
                ('kind_minor', models.CharField(choices=[('subject_majors', 'Subject_majors'), ('subject_minors', 'Subject_minors'), ('target_grades', 'Target_grades'), ('target_tests', 'Target_tests')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
