# Generated by Django 4.0.8 on 2023-07-04 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workbook_evaluations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('isbn', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workbooks', to=settings.AUTH_USER_MODEL)),
                ('workbook_evalution', models.ManyToManyField(blank=True, related_name='workbooks', to='workbook_evaluations.workbook_evaluation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
