# Generated by Django 4.0.10 on 2023-10-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbook',
            name='user',
        ),
    ]
