# Generated by Django 4.0.10 on 2023-10-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0003_workbook_learning_type_workbook_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='image_url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
