# Generated by Django 4.0.10 on 2023-10-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0004_workbook_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='subject_detail',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
