# Generated by Django 4.1.4 on 2023-01-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('ranges', models.CharField(max_length=140)),
                ('learning_time', models.DecimalField(decimal_places=1, max_digits=5)),
                ('guideline', models.TextField(blank=True)),
                ('references', models.CharField(blank=True, max_length=140)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.track')),
            ],
        ),
    ]
