# Generated by Django 4.0.10 on 2023-09-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_days', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_day',
            name='user',
        ),
    ]
