# Generated by Django 4.0.10 on 2023-10-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_days', '0003_remove_task_day_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_day',
            name='image_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
