# Generated by Django 4.0.10 on 2023-09-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_days', '0001_initial'),
        ('task_assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='task_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='task_days.task_day'),
        ),
    ]
